version: "2.2"

services:
  prom01:
    image: prom/prometheus:${PROMETHEUS_VESION}
    ports:
      - ${PROMETHEUS_PORT}:9090
      - ${PROMETHEUS_PUSHGATEWAY_PORT}:9091
    networks:
      - stack-net
    volumes:
      - prom01data:/prometheus
      - ./prometheus_configfiles:/etc/prometheus
  grafana:
    depends_on:
       - prom01
    image: grafana/grafana-enterprise:${GRAFANA_VERSION}
    volumes:
      - grafanadata:/var/lib/grafana
      - grafanaplugins:/var/lib/grafana/plugins
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
     - stack-net

volumes:
  prom01data:
    driver: local
  grafanadata:
    driver: local
  grafanaplugins:
    driver: local

networks:
  stack-net:
    driver: bridge