version: "2.2"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      #Bind-mount: in case you want a custom elastic.yml configuration:
      #- ./elasticsearch_configfiles/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - ${ES_PORT}:9200
    environment:
     - xpack.security.enabled=false
     - discovery.type=single-node
     - node.name=es01
     - cluster.name=es-cluster
    networks:
     - stack-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

  grafana:
    depends_on:
       - es01
    image: grafana/grafana-enterprise:${GRAFANA_VERSION}
    volumes:
      - grafanadata:/var/lib/grafana
      - grafanaplugins:/var/lib/grafana/plugins
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    networks:
     - stack-net

volumes:
  esdata01:
    driver: local
  grafanadata:
    driver: local
  grafanaplugins:
    driver: local

networks:
  stack-net:
    driver: bridge