version: "2.2"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      #Bind-mount: in case you want a custom elastic.yml configuration:
      #- ./elasticsearch_configfiles/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - ${ES_PORT}:9200
    environment:
     - xpack.security.enabled=false
     - discovery.type=single-node
     - node.name=es01
     - cluster.name=es-cluster
    networks:
     - stackELK-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535

  kibana:
    depends_on:
       - es01
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - kibanadata:/usr/share/kibana/data
      #Bind-mount: in case you want a custom kibana.yml configuration:
      #- ./kibana_configfiles/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    networks:
     - stackELK-net

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local

networks:
  stackELK-net:
    driver: bridge